parameters:
#    snappminds_utils_abm.example.class: Snappminds\Utils\Bundle\ABMBundle\Example

services:
#    snappminds_utils_abm.example:
#        class: %snappminds_utils_abm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
